version: "2"

services:
  frontendReport:
    image: httpd:2.4
    volumes:
        - ./dist/:/usr/local/apache2/htdocs/ 
        - /etc/localtime:/etc/localtime:ro
    networks:
        - traefik_network
    restart: always

    labels:
      - "traefik.http.routers.frontendReport.rule=Host(`frontendReport.twlife.duckdns.org`)"
      - "traefik.http.routers.frontendReport.tls=true"
networks:
  traefik_network:
    external: true
